# Generated by Django 5.2.4 on 2025-07-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa257', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlestatictagsindexpage',
            name='full_body_groups',
            field=models.CharField(blank=True, default='1', help_text="A comma separated one-based list of the tag group numbers for which the full body instead of summary should be shown in an index page.  ex: '1,3' means that for articles in the first and third groups, the body will be shown instead of the summary", max_length=30, verbose_name='full body groups'),
        ),
    ]
