# Generated by Django 5.2.4 on 2025-08-09 00:34

import datetime
import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa257', '0002_alter_articlestatictagsindexpage_full_body_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icalcombinerpage',
            name='calendar_format',
            field=models.CharField(choices=[('DTLS', 'date list'), ('GRID', 'calendar grid')], default='DTLS', help_text='(choices unavailable for now) The format for how the events are displayed', max_length=4, verbose_name='calendar format'),
        ),
        migrations.CreateModel(
            name='IcalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('summary', models.CharField(help_text='The summary, also used as the title, of the event', max_length=128)),
                ('description', models.TextField(blank=True, help_text="Details about the event. This won't be seen if the event is linked to an article or url")),
                ('uid', models.CharField(help_text='The UID of the event from ics data', max_length=120)),
                ('url', models.CharField(blank=True, help_text='The URL to link to. Leave blank if linking to an article using the Article field', max_length=200)),
                ('date_start', models.DateField(default=datetime.date.today, help_text='When the event starts', verbose_name='start date')),
                ('time_start', models.TimeField(blank=True, help_text='Start Time - Leave blank for all day events', verbose_name='start time')),
                ('date_end', models.DateField(default=datetime.date.today, help_text='When the event ends', verbose_name='end date')),
                ('time_end', models.TimeField(blank=True, help_text='End Time - Leave blank for all day events', verbose_name='end time')),
                ('use_time', models.BooleanField(default=True, help_text='Use the time field (Uncheck for all day events)', verbose_name='use time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', modelcluster.fields.ParentalKey(blank=True, help_text='An article to link to.  Ensure the url field is blank to use this field', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webikwa257.articlepage')),
                ('icalendar', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ical_events', to='webikwa257.icalendarpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
