# Generated by Django 5.2.5 on 2025-08-23 19:43

import webikwa257.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa257', '0003_alter_icalcombinerpage_calendar_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icalendarpage',
            name='data',
            field=models.TextField(blank=True, default=webikwa257.models.get_empty_ical, help_text='The ics data. If source is filled in, this will be overwritten. If you wish to edit this field, ensure the source field is blank', verbose_name='body'),
        ),
    ]
