# Generated by Django 5.2.6 on 2025-10-16 09:44

import wagtailmarkdown.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webikwa257", "0004_alter_icalendarpage_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitetemplatesettings",
            name="footer_text_separator",
        ),
        migrations.AlterField(
            model_name="sitetemplatesettings",
            name="footer_text",
            field=wagtailmarkdown.fields.MarkdownField(
                blank=True,
                default="Created wth Wagtail and webikwa257",
                help_text="The footer in markdown",
                verbose_name="footer text",
            ),
        ),
    ]
