# Generated by Django 6.0.1 on 2026-02-19 12:31

import webikwa257.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa257', '0005_remove_sitetemplatesettings_footer_text_separator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icalendarevent',
            name='time_end',
            field=models.TimeField(blank=True, default=webikwa257.models.IcalendarEvent.get_default_end, help_text='End Time - Leave blank for all day events', null=True, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='icalendarevent',
            name='time_start',
            field=models.TimeField(blank=True, default=webikwa257.models.IcalendarEvent.get_default_start, help_text='Start Time - Leave blank for all day events', null=True, verbose_name='start time'),
        ),
    ]
