# Generated by Django 6.0.1 on 2026-03-04 20:52

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('webikwa257', '0006_alter_icalendarevent_time_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePlacementPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('show_pagetitle', models.BooleanField(default=True, help_text='If the page title should be shown')),
                ('zone_qty', models.IntegerField(default=5, help_text='The number of zones on the page', verbose_name='number of zones')),
                ('full_body_zones', models.CharField(blank=True, default='1', help_text="A comma separated one-based list of the zone numbers for which the full body instead of summary should be shown in an index page.  ex: '1,3' means that for articles in the first and third zones, the body will be shown instead of the summary", max_length=30, verbose_name='full body zones')),
                ('zone_titles', models.TextField(blank=True, help_text='Titles for zones, one per line, starting each line with the zone number and a colon, and optionally a space ex: "1: Featured Articles" ')),
                ('custom_css', models.TextField(blank=True, help_text='Custom css to be added to the html head section when this page is displayed. Zones will have class names in the format of "zone_1" where "1" is replaced by the zone number')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArticlePlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.IntegerField(default=1, help_text='The zone on the page.  If the number entered is greater than the number of zones on the page, the last zone will be used')),
                ('expiration_date', models.DateField(blank=True, help_text='The date after which the article will be removed from this page zone. This is only takes affect when remove_exipred_placements is run', null=True, verbose_name='Expiration Date')),
                ('article', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_placements', to='webikwa257.articlepage')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_placements', to='webikwa257.articleplacementpage')),
            ],
            options={
                'ordering': ('page', 'zone'),
            },
        ),
    ]
