# Generated by Django 6.0.1 on 2026-03-05 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa257', '0007_articleplacementpage_articleplacement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleplacement',
            options={'ordering': ('page', 'zone', 'article')},
        ),
    ]
