# Generated by Django 6.0.1 on 2026-03-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa257', '0008_alter_articleplacement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepage',
            options={'ordering': ('-last_published_at',), 'verbose_name': 'Article'},
        ),
        migrations.RemoveField(
            model_name='articleplacementpage',
            name='full_body_zones',
        ),
        migrations.AddField(
            model_name='articleplacement',
            name='boldness',
            field=models.CharField(choices=[('bold', 'Bold'), ('normal', 'Normal'), ('light', 'Light')], default='normal', help_text='A signal to the template about how to style this article on this page, from Very Bold to Very Light', verbose_name='boldness'),
        ),
        migrations.AddField(
            model_name='articleplacement',
            name='show_body',
            field=models.BooleanField(default=False, help_text='Show the body instead the summary', verbose_name='show full body'),
        ),
    ]
