# Generated by Django 6.0.4 on 2026-04-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa257', '0009_alter_articlepage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icalcombinerpage',
            name='show_hide_calendars',
            field=models.BooleanField(default=True, help_text='When more than one calendar is combined, show the option that allows the user to hide certain calendars', verbose_name='show the hide calendars option'),
        ),
    ]
