# Generated by Django 6.0.4 on 2026-04-22 15:55

import wagtailmarkdown.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa257', '0010_icalcombinerpage_show_hide_calendars'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetemplatesettings',
            name='after_article',
            field=wagtailmarkdown.fields.MarkdownField(default='\n            <div id="after_article">\n                You can share this post on most social media by copying the URL and pasting it into a post.\n                <button type="button" id="copy_url_button">copy url</button>\n            </div>\n            <script>\n                var url_button = document.getElementById("copy_url_button")\n                url_button.addEventListener("click", function(e) {\n                    e.preventDefault()\n                    var url_input = document.createElement("input")\n                    var url_div = document.getElementById("copy_url_div")\n                    url_div.appendChild(url_input)\n                    url_input.value=window.location.href\n                    url_input.select()\n                    document.execCommand("copy")\n                    url_div.removeChild(url_input)\n                })\n            </script>\n        ', help_text='content to follow each article', verbose_name='after_article'),
        ),
    ]
